Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.boot_timeout = 600
  # Example for VirtualBox:
    config.vm.provider "virtualbox" do |vb|
  # Customize the amount of memory on the VM:
      vb.memory = "3072"
    end
  #configure provisioners on tha machine
    config.vm.provision :docker

    config.vm.define "server-1" do |ci|
      ci.vm.network "private_network", ip: '192.168.56.60'
      ci.vm.hostname = "ciserver"
      ci.vm.provision :file, source:"../docker/docker-compose.ci.yml", destination:"docker-compose.yml"
      ci.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
      ci.vm.provision :shell, inline:"sudo chmod 777 /var/run/docker.sock"
    end

    config.vm.define "server-2" do |server2|
      server2.vm.network "private_network", ip: '192.168.56.61'
      server2.vm.hostname = "server2"
    end
end