Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

  # Example for VirtualBox:
    config.vm.provider "virtualbox" do |vb|
  # Customize the amount of memory on the VM:
      vb.memory = "4096"
    end
  #configure provisioners on tha machine
    config.vm.provision :docker

    config.vm.define "server-1" do |ci|
      ci.vm.network "private_network", ip: '192.168.56.60'
      ci.vm.hostname = "ciserver"
      ci.vm.provision :file, source:"../docker/docker-compose.ci.yml", destination:"docker-compose.yml"
      ci.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
    end
end