FROM gocd/gocd-agent-ubuntu-20.04:v22.2.0
USER root
RUN apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive TZ="America/La_Paz" apt-get install -y openjdk-11-jdk && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_18.x | bash && \
    apt-get install -y nodejs && \
    apt install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
    apt-add-repository 'deb https://download.mono-project.com/repo/ubuntu stable-focal main' && \
    apt install -y mono-complete && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \ 
    export SONAR_SCANNER_VERSION=4.7.0.2747 && \
    export SONAR_SCANNER_HOME=/godata/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux && \
    curl --create-dirs -sSLo /godata/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip && \
    unzip -o /godata/.sonar/sonar-scanner.zip -d /godata/.sonar/ && \
    export PATH=$SONAR_SCANNER_HOME/bin:$PATH && \
    export SONAR_SCANNER_OPTS="-server"
User go
